jobs:
  - name: test_alpine_img
    type: runSh
    steps:
      - TASK:
          name: test_image
          runtime:
            options:
              imageName: "manishas/build_alpine_ci"
              imageTag: "654253"
              pull: true
          script:
            - python -V
            - echo "Runsh running successfully!"

  
