jobs:
  - name: test_alpine_img
    type: runSh
    steps:
      - TASK:
          name: test_image
          runtime:
            options:
              imageName: build_alpine_ci
              imageTag: 654253
          script:
            - python -V
            - echo "Runsh running successfully!"

  
